(function(){
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat('ru-RU').format(Math.round(Number(n)||0))+' ₸';
const menu=document.querySelector('.menu'),nav=document.querySelector('.nav');
if(menu&&nav)menu.addEventListener('click',()=>nav.classList.toggle('open'));
document.querySelectorAll('.year').forEach(el=>el.textContent=new Date().getFullYear());
const typeText=$('typeText');
if(typeText){const t='AI mentor, аналитика, экономика товара, логистика, карточка и обучение продавца в одном месте.';let i=0;(function tick(){typeText.textContent=t.slice(0,i++);if(i<=t.length)setTimeout(tick,35)})()}

const kb=[
{keys:['старт','начать','начинающ','нович','первый товар'],title:'Старт продавца на маркетплейсе',answer:'1. Выберите нишу с понятным спросом и адекватной конкуренцией.\n2. Посчитайте unit economics до закупа.\n3. Проверьте габариты, упаковку и документы категории.\n4. Подготовьте карточку: название, характеристики, фото, инфографика, описание.\n5. Запускайте тест маленькой партией и каждый день смотрите CTR, конверсию, выкуп, остатки и отзывы.'},
{keys:['карточк','описан','назван','seo','сео','ключ','характерист'],title:'Карточка товара',answer:'Сильная карточка: понятное название, точные характеристики, первое фото с товаром, инфографика с 3-5 фактами, описание без воды, правильная категория и заполненные атрибуты. Не обещайте того, чего нет в товаре, иначе будут возвраты и плохие отзывы.'},
{keys:['цена','прибыл','марж','roi','рентаб','себесто','нацен'],title:'Unit economics и цена',answer:'Прибыль = цена продажи минус себестоимость минус комиссия минус логистика минус реклама минус упаковка минус налог. Смотрите не только маржу в процентах, но и прибыль в деньгах. Если ROI ниже 30-40 процентов, товар рискованный после рекламы и возвратов.'},
{keys:['логист','габарит','упаков','литр','склад','коледино'],title:'Логистика и упаковка',answer:'Проверьте длину, ширину, высоту и вес с упаковкой. Опасно занижать габариты: фактическая упаковка может привести к перерасчету логистики. На странице Расчеты можно проверить объем в литрах и примерную стоимость.'},
{keys:['реклам','ддр','drr','ставк','продвиж','показ','ctr','конверс'],title:'Реклама и продвижение',answer:'Сначала проверьте карточку: фото, цена, отзывы, рейтинг, остатки. Если карточка слабая, реклама сольет бюджет. Если CTR низкий, проблема в фото и оффере. Если CTR нормальный, но заказов нет, проблема в цене, отзывах или карточке.'},
{keys:['аналит','статист','выруч','заказ','остат','оборач','возврат','выкуп'],title:'Аналитика продаж',answer:'Ежедневно смотрите выручку, заказы, средний чек, рекламные расходы, возвраты, выкуп, остатки и дни запаса. Опасные сигналы: высокий процент возвратов, ДРР выше 20 процентов, остатка меньше чем на 7 дней, падение конверсии и рост жалоб.'},
{keys:['ниш','товар','выбрать','что продав','конкурент'],title:'Выбор товара и ниши',answer:'Сильный товар имеет понятный спрос, не слишком дорогую логистику, нормальную маржу, стабильную аудиторию. Перед закупом проверьте конкурентов: цены, отзывы, количество продаж, качество фото и слабые места карточек.'},
{keys:['отзыв','рейтинг','жалоб','возврат'],title:'Отзывы и рейтинг',answer:'Отзывы сильно влияют на конверсию. Нужно быстро отвечать на вопросы, честно описывать характеристики, контролировать упаковку и комплектацию. Если возвратов много, ищите причину: фото, размеры, ожидания, упаковка или качество.'},
{keys:['фото','инфограф','картин','дизайн','облож'],title:'Фото и инфографика',answer:'Первое фото должно сразу показывать товар и главное преимущество. Инфографика короткая: 3 точных факта на слайд, крупный текст, понятные иконки, без ложных функций и без перегруза.'},
{keys:['документ','сертифик','деклара','маркиров','закон'],title:'Документы и безопасность',answer:'Для некоторых категорий нужны документы, декларации, сертификаты или маркировка. Перед запуском проверьте требования категории. Если сомневаетесь, не размещайте товар без подтверждающих документов.'}
];
function now(){return new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}
function addMsg(text,sender){const box=$('chatMessages');if(!box)return;const item=document.createElement('div');item.className='message '+sender;item.innerHTML='<div class="bubble"></div><div class="meta"></div>';item.querySelector('.bubble').textContent=text;item.querySelector('.meta').textContent=sender==='user'?'Вы '+now():'AI Mentor '+now();box.appendChild(item);box.scrollTop=box.scrollHeight}
function typing(){const box=$('chatMessages');if(!box)return;const item=document.createElement('div');item.className='message bot';item.id='typing';item.innerHTML='<div class="bubble"><span class="typing"><i></i><i></i><i></i></span></div>';box.appendChild(item);box.scrollTop=box.scrollHeight}
function rmTyping(){const t=$('typing');if(t)t.remove()}
function aiAnswer(q){const txt=q.toLowerCase();const matches=kb.map(it=>({...it,score:it.keys.reduce((s,k)=>s+(txt.includes(k)?1:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);if(matches.length){const m=matches[0];return m.title+'\n\n'+m.answer+'\n\nПрактический шаг: откройте страницу Расчеты или Аналитика и проверьте цифры по своему товару.'}return 'Я не подключен к живому кабинету Wildberries и не вижу реальные данные, но могу разобрать вопрос как наставник продавца.\n\nПроверил бы 5 вещей:\n1. Что именно продается и в какой категории.\n2. Есть ли спрос и кто конкуренты.\n3. Сходится ли экономика после комиссии, логистики, рекламы и возвратов.\n4. Насколько сильная карточка: фото, название, характеристики, цена, отзывы.\n5. Какой следующий измеримый шаг: тест цены, улучшение фото, расчет маржи или анализ остатков.\n\nНапишите конкретнее: почему нет заказов, как выбрать нишу, как улучшить карточку или как посчитать цену.'}
function ask(q){if(!q.trim())return;addMsg(q,'user');typing();setTimeout(()=>{rmTyping();addMsg(aiAnswer(q),'bot')},650+Math.min(q.length*10,900))}
const chatForm=$('chatForm');if(chatForm)chatForm.addEventListener('submit',e=>{e.preventDefault();const input=$('chatInput');ask(input.value);input.value=''})
document.querySelectorAll('[data-question]').forEach(b=>b.addEventListener('click',()=>ask(b.dataset.question)));

function calcEconomics(){const cost=+$('cost')?.value||0, price=+$('price')?.value||0, commission=+$('commission')?.value||0, logistics=+$('logistics')?.value||0, ad=+$('ad')?.value||0, tax=+$('tax')?.value||0, returns=+$('returns')?.value||0, pack=+$('pack')?.value||0;const comm=price*commission/100, adSum=price*ad/100, taxSum=price*tax/100, reserve=price*returns/100*.35;const profit=price-cost-comm-logistics-adSum-taxSum-reserve-pack;const margin=price?profit/price*100:0, roi=cost?profit/cost*100:0;const out=$('economicsResult');if(out){const status=profit>0&&margin>=18?'Экономика выглядит рабочей.':profit>0?'Прибыль есть, но запас слабый.':'Экономика убыточная, цену или расходы нужно менять.';out.innerHTML=`<div class="result-card"><b>Цена продажи:</b> ${money(price)}</div><div class="result-card"><b>Комиссия:</b> ${money(comm)}</div><div class="result-card"><b>Реклама:</b> ${money(adSum)}</div><div class="result-card"><b>Налог:</b> ${money(taxSum)}</div><div class="result-card"><b>Резерв на возвраты:</b> ${money(reserve)}</div><div class="result-card"><b>Чистая прибыль:</b> ${money(profit)}</div><div class="result-card"><b>Маржа:</b> ${margin.toFixed(1)}% • <b>ROI:</b> ${roi.toFixed(1)}%</div><div class="recommendation"><b>Вывод:</b> ${status}</div>`}}
['cost','price','commission','logistics','ad','tax','returns','pack'].forEach(id=>{const el=$(id);if(el)el.addEventListener('input',calcEconomics)});calcEconomics();
function calcLogistics(){const l=+$('length')?.value||0,w=+$('width')?.value||0,h=+$('height')?.value||0,weight=+$('weight')?.value||0,coef=+$('warehouseCoef')?.value||1;const liters=l*w*h/1000, base=liters<=1?46:46+(liters-1)*14, cost=base*coef, sum=l+w+h;let warn='Габариты выглядят нормально для демо расчета.';if(sum>199)warn='Внимание: сумма сторон больше 199 см. Проверьте ограничения и риски логистики.';if(weight>=25)warn+=' Вес 25 кг или больше, возможны ограничения.';const out=$('logisticsResult');if(out)out.innerHTML=`<div class="result-card"><b>Объем:</b> ${liters.toFixed(2)} л</div><div class="result-card"><b>Стоимость логистики:</b> ${money(cost)}</div><div class="recommendation">${warn}</div>`}
['length','width','height','weight','warehouseCoef'].forEach(id=>{const el=$(id);if(el)el.addEventListener('input',calcLogistics)});calcLogistics();
function seoGenerate(){const p=$('seoProduct')?.value.trim()||'Товар',m=$('seoModel')?.value.trim()||'',f=$('seoFeature')?.value.trim()||'',a=$('seoAudience')?.value.trim()||'';let title=[p,m,f].filter(Boolean).join(' ').replace(/[;®™]/g,'').replace(/\s+/g,' ').trim();if(title.length>60)title=title.slice(0,60).trim();const desc=`${p} ${m} подойдет для ${a||'ежедневного использования'}. В карточке важно показать реальные характеристики, комплектацию, материал, размеры, преимущества и сценарии применения. Текст должен быть понятным, без воды и без неподтвержденных обещаний.`;const keys=[p,m,f,a].filter(Boolean).join(' ').split(' ').filter(x=>x.length>2).slice(0,12).join(', ');const out=$('seoResult');if(out)out.innerHTML=`<div class="result-card"><b>Название:</b><br>${title}<br><small>${title.length} символов</small></div><div class="result-card"><b>Описание:</b><br>${desc}</div><div class="result-card"><b>Ключевые слова:</b><br>${keys}</div>`}
['seoProduct','seoModel','seoFeature','seoAudience'].forEach(id=>{const el=$(id);if(el)el.addEventListener('input',seoGenerate)});seoGenerate();
function rand(seed){const x=Math.sin(seed)*10000;return x-Math.floor(x)}
function drawChart(canvas,data,a,b){if(!canvas)return;const ctx=canvas.getContext('2d'),dpr=devicePixelRatio||1;canvas.width=canvas.clientWidth*dpr;canvas.height=canvas.clientHeight*dpr;ctx.scale(dpr,dpr);const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);ctx.strokeStyle='rgba(255,255,255,.12)';for(let i=1;i<5;i++){ctx.beginPath();ctx.moveTo(0,h*i/5);ctx.lineTo(w,h*i/5);ctx.stroke()}const max=Math.max(...data)*1.15,step=w/(data.length-1);const grad=ctx.createLinearGradient(0,0,w,0);grad.addColorStop(0,a);grad.addColorStop(1,b);ctx.strokeStyle=grad;ctx.lineWidth=4;ctx.beginPath();data.forEach((v,i)=>{const x=i*step,y=h-(v/max)*(h-24)-12;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)});ctx.stroke();data.forEach((v,i)=>{const x=i*step,y=h-(v/max)*(h-24)-12;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fill()})}
function analytics(){const cat=$('category')?.value||'electronics',rev=+$('revenue')?.value||0,orders=+$('orders')?.value||0,ads=+$('adSpend')?.value||0,ret=+$('returnRate')?.value||0,stock=+$('stock')?.value||0;const avg=orders?rev/orders:0,drr=rev?ads/rev*100:0,daily=orders/30,days=daily?stock/daily:0,conv=Math.max(1.2,Math.min(12,2.8+(avg/30000)+(12-ret)/4));let rec=[];if(drr>18)rec.push('ДРР высокий, проверьте ставки рекламы и конверсию карточки.');if(ret>10)rec.push('Возвраты высокие, проверьте фото, описание, размерную сетку и упаковку.');if(days<10)rec.push('Остатков меньше чем на 10 дней, стоит планировать поставку.');if(conv<3)rec.push('Конверсия слабая, улучшите первое фото, цену и отзывы.');if(!rec.length)rec.push('Показатели выглядят стабильными, можно аккуратно масштабировать рекламу.');const out=$('analyticsResult');if(out)out.innerHTML=`<div class="dashboard-grid"><div class="card kpi"><span class="kicker">Выручка</span><strong>${money(rev)}</strong><p>30 дней</p></div><div class="card kpi"><span class="kicker">Заказы</span><strong>${orders}</strong><p>Средний чек ${money(avg)}</p></div><div class="card kpi"><span class="kicker">ДРР</span><strong>${drr.toFixed(1)}%</strong><p>Реклама к выручке</p></div></div><div class="result-card"><b>Дней остатков:</b> ${days.toFixed(1)} • <b>Возвраты:</b> ${ret.toFixed(1)}% • <b>Оценка конверсии:</b> ${conv.toFixed(1)}%</div><div class="recommendation"><b>Рекомендация:</b><br>${rec.map(x=>'• '+x).join('<br>')}</div>`;const seed=cat.length+rev/100000+orders;const sales=Array.from({length:14},(_,i)=>Math.max(1,daily*(.65+rand(seed+i)*.75)));drawChart($('salesChart'),sales,'#f0abfc','#22d3ee');drawChart($('revenueChart'),sales.map(x=>x*avg),'#ec4899','#8b5cf6')}
['category','revenue','orders','adSpend','returnRate','stock'].forEach(id=>{const el=$(id);if(el)el.addEventListener('input',analytics)});analytics();
const lessons=[['Ниша и товар','Как выбирать товар, смотреть конкурентов и оценивать спрос.'],['Unit economics','Цена, маржа, ROI, комиссия, реклама и логистика.'],['Карточка товара','Название, фото, инфографика, характеристики и описание.'],['Логистика','Габариты, упаковка, склад, остатки и риски перерасчета.'],['Реклама','CTR, CPC, ДРР, конверсия и тестирование ставок.'],['Аналитика','Выручка, заказы, возвраты, остатки, рейтинг и решения по данным.']];
function renderLessons(){const box=$('lessonGrid');if(!box)return;const done=JSON.parse(localStorage.getItem('wbLessonsDone')||'[]');box.innerHTML=lessons.map((l,i)=>`<article class="lesson ${done.includes(i)?'done':''}"><h3>${i+1}. ${l[0]}</h3><p>${l[1]}</p><button class="btn btn-ghost" data-lesson="${i}">${done.includes(i)?'Пройдено':'Отметить как пройдено'}</button></article>`).join('');box.querySelectorAll('[data-lesson]').forEach(btn=>btn.addEventListener('click',()=>{let cur=JSON.parse(localStorage.getItem('wbLessonsDone')||'[]'),id=+btn.dataset.lesson;if(cur.includes(id))cur=cur.filter(x=>x!==id);else cur.push(id);localStorage.setItem('wbLessonsDone',JSON.stringify(cur));renderLessons()}));const p=$('progressLine'),txt=$('progressText');if(p)p.style.width=Math.round(done.length/lessons.length*100)+'%';if(txt)txt.textContent=`${done.length} из ${lessons.length} модулей пройдено`}
renderLessons();
const quiz=[{q:'Что нужно посчитать до закупа товара?',a:['Только красивое название','Unit economics','Цвет сайта'],c:1},{q:'Что означает ДРР?',a:['Доля рекламных расходов','Длина размера рюкзака','Доход розничного рынка'],c:0},{q:'Если возвраты высокие, что проверить первым?',a:['Фото, описание, размер, упаковку','Только шрифт сайта','Только цвет кнопки'],c:0},{q:'Что опасно делать с габаритами упаковки?',a:['Занижать фактические размеры','Указывать реальные размеры','Проверять вес'],c:0}];
function renderQuiz(){const box=$('quizBox');if(!box)return;box.innerHTML=quiz.map((it,i)=>`<div class="result-card"><b>${i+1}. ${it.q}</b>${it.a.map((ans,j)=>`<label><input type="radio" name="q${i}" value="${j}"> ${ans}</label>`).join('')}</div>`).join('')+'<button class="btn btn-primary" id="checkQuiz" type="button">Проверить тест</button><div class="calc-result" id="quizResult"></div>';$('checkQuiz').addEventListener('click',()=>{let s=0;quiz.forEach((it,i)=>{const selected=document.querySelector(`input[name="q${i}"]:checked`);if(selected&&+selected.value===it.c)s++});$('quizResult').innerHTML=`Результат: ${s} из ${quiz.length}. ${s>=3?'Хорошо, можно переходить к расчетам.':'Повторите модули по экономике и карточке товара.'}`})}
renderQuiz();
const contact=$('contactForm'),msg=$('formMessage');if(contact&&msg)contact.addEventListener('submit',e=>{e.preventDefault();const name=contact.elements.name.value.trim();msg.textContent=name?`${name}, сообщение принято. Спасибо!`:'Сообщение принято.';contact.reset()});
})();
